/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.inzori.branchio;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.util.TiConvert;

import android.content.Intent;
import android.app.Activity;

import org.json.JSONObject;

import io.branch.indexing.BranchUniversalObject;
import io.branch.referral.Branch;
import io.branch.referral.BranchError;
import io.branch.referral.util.LinkProperties;

// This proxy can be created by calling BranchIO.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule=BranchIOModule.class)
public class BranchUniversalObjectProxy extends KrollProxy
{
	// Standard Debugging variables
	private static final String LCAT = "BranchUniversalObjectProxy";

//	@Override
//	public void onNewIntent(Intent intent) {
//		super.onNewIntent(intent);
//		this.setIntent(intent);
//		Branch.sessionBuilder(this).withCallback(new BranchReferralInitListener() {
//			@Override
//			public void onInitFinished(JSONObject referringParams, BranchError error) {
//				if (error != null) {
//					Log.e("BranchSDK_Tester", error.getMessage());
//				} else if (referringParams != null) {
//					Log.i("BranchSDK_Tester", referringParams.toString());
//				}
//			}
//		}).reInit();
//	}


	// Constructor
	public BranchUniversalObjectProxy()
	{
		super();
	}

}
